allocator_1048576:memory_allocation_copy.o
	gcc -o allocator_1048576 memory_allocation_copy.o -Wall -Werror
memory_allocation_copy.o:memory_allocation_copy.c
	gcc -c memory_allocation_copy.c
clean:
	rm memory_allocation_copy.o allocator_1048576
