allocator_1048576:memory_allocation.o
	gcc -o allocator_1048576 memory_allocation.o -Wall -Werror
memory_allocation.o:memory_allocation.c
	gcc -c memory_allocation.c
clean:
	rm memory_allocation.o allocator_1048576
