Virtual_Memory_Manager:virtual_memory_manager.c
	gcc -o Virtual_Memory_Manager virtual_memory_manager.o -Wall -Werror
virtual_memory_manager.o:virtual_memory_manager.c
	gcc -c virtual_memory_manager.c
clean:
	rm Virtual_Memory_Manager virtual_memory_manager.o
